framework: jest     
preRun:
  command:
    - yarn install          
postMerge:
  pattern: 
    - "./app/**/*.spec.ts"
    - "./app/**/*.test.ts"
preMerge:
  pattern:
    - "./app/**/*.spec.ts"
    - "./app/**/*.test.ts"
postRun:
  command:
    - yarn --version
version: 1.0